lib/inkfish_web/router.ex
defmodule InkfishWeb.Router do
  use InkfishWeb, :router
  
  alias InkfishWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plugs.Assign, client_mode: :browser
    plug :fetch_session
    plug Plugs.FetchUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Breadcrumb, {"Home", :page, :index}
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug Plugs.Assign, client_mode: :ajax
    plug :fetch_session
    plug Plugs.FetchUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  
  pipeline :admin do
    plug Plugs.RequireUser, is_admin: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InkfishWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    resources "/session", SessionController, only: [:create, :delete], singleton: true
    post "/session/resume", SessionController, :resume
    resources "/users", UserController, only: [:show, :edit, :update]
    resources "/uploads", UploadController, only: [:create, :show]
    get "/uploads/:id/_meta/thumb", UploadController, :thumb
    get "/uploads/:id/_meta/unpacked/*path", UploadController, :unpacked
    get "/uploads/:id/:name", UploadController, :download
    resources "/courses", CourseController, only: [:index, :show] do
      resources "/join_reqs", JoinReqController, only: [:new, :create]
    end
    resources "/regs", RegController, only: [:show]
    resources "/teams", TeamController, only: [:show]
    resources "/assignments", AssignmentController, only: [:show] do
      resources "/subs", SubController, only: [:new, :create]
    end
    resources "/subs", SubController, only: [:show]
    get "/subs/:id/files", SubController, :files
    resources "/grade_columns", GradeColumnController, only: [:show]
    resources "/grades", GradeController, only: [:show]
  end

  scope "/staff", InkfishWeb.Staff, as: :staff do
    pipe_through :browser

    resources "/courses", CourseController, only: [:index, :show, :edit, :update] do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:index]
      resources "/teamsets", TeamsetController, only: [:index, :new, :create]
      resources "/buckets", BucketController, only: [:index, :new, :create]
      post "/join_reqs/accept_all", JoinReqController, :accept_all
    end
    get "/courses/:id/gradesheet", CourseController, :gradesheet
    get "/courses/:id/tasks", CourseController, :tasks
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/join_reqs", JoinReqController, only: [:show, :delete]
    post "/join_reqs/:id/accept", JoinReqController, :accept
    resources "/teamsets", TeamsetController, except: [:index, :new, :create]
    resources "/buckets", BucketController, except: [:index, :new, :create] do
      resources "/assignments", AssignmentController, only: [:new, :create]
    end
    resources "/assignments", AssignmentController, except: [:index, :new, :create] do
      resources "/grade_columns", GradeColumnController, only: [:index, :new, :create]
      resources "/grading_tasks", GradingTaskController,
        except: [:new, :delete], singleton: true
    end
    post "/assignments/:id/create_fake_subs", AssignmentController, :create_fake_subs
    resources "/grade_columns", GradeColumnController, except: [:index, :new, :create]
    resources "/subs", SubController, only: [:show, :update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [:edit, :show]
    post "/grades/:id/rerun_script", GradeController, :rerun_script
  end

  scope "/admin", InkfishWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    
    resources "/users", UserController, except: [:new, :create]
    post "/users/:id/impersonate", UserController, :impersonate
    resources "/courses", CourseController
    resources "/uploads", UploadController, only: [:index]
  end

  scope "/ajax", InkfishWeb, as: :ajax do
    pipe_through :ajax

    post "/uploads", UploadController, :create
  end

  scope "/ajax/staff", InkfishWeb.Staff, as: :ajax_staff do
    pipe_through :ajax

    resources "/subs", SubController, only: [:update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [] do
      resources "/line_comments", LineCommentController, only: [:create]
    end
    resources "/line_comments", LineCommentController, only: [:show, :update, :delete]
    resources "/teamsets", TeamsetController, only: [] do
      resources "/teams", TeamController, only: [:index, :create]
    end
    resources "/teams", TeamController, only: [:show, :update, :delete]
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/live_dashboard", metrics: InkfishWeb.Telemetry
    end
  end
end

lib/inkfish_web/controllers/reg_controller.ex
defmodule InkfishWeb.RegController do
  use InkfishWeb, :controller

  alias Inkfish.Users

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [course: "course_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [reg: "id"]
    when action not in [:index, :new, :create]
  plug Plugs.RequireReg
  plug :require_self

  def require_self(conn, _args \\ []) do
    user = conn.assigns[:current_user]
    creg = conn.assigns[:current_reg]
    reg  = conn.assigns[:reg]
    is_staff = reg.is_staff || reg.is_prof || user.is_admin

    if is_staff || reg.id == creg.id do
      conn
    else
      conn
      |> put_flash(:error, "Access denied.")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt
    end
  end

  def show(conn, %{"id" => id}) do
    reg = Users.get_reg!(id)
    render(conn, "show.html", reg: reg)
  end
end

lib/inkfish_web/controllers/staff/assignment_controller.ex
defmodule InkfishWeb.Staff.AssignmentController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs

  plug Plugs.FetchItem, [bucket: "bucket_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [assignment: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}
    when action not in [:index, :new, :create, :show]

  alias Inkfish.Assignments
  alias Inkfish.Assignments.Assignment

  def new(conn, params) do
    teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
    today = Inkfish.LocalTime.today()
    {:ok, due} = NaiveDateTime.new(Date.add(today, 7), ~T[23:59:59])
    as = %Assignment{
      bucket_id: params["bucket_id"],
      teamset_id: hd(teamsets).id,
      weight: Decimal.new("1.0"),
      due: due,
      allow_git: false,
    }
    changeset = Assignments.change_assignment(as)
    sta_tok = upload_token(conn, "assignment_starter")
    sol_tok = upload_token(conn, "assignment_solution")
    render(conn, "new.html", changeset: changeset, teamsets: teamsets,
      sta_tok: sta_tok, sol_tok: sol_tok)
  end

  def create(conn, %{"assignment" => assignment_params}) do
    case Assignments.create_assignment(assignment_params) do
      {:ok, assignment} ->
        conn
        |> put_flash(:info, "Assignment created successfully.")
        |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))

      {:error, %Ecto.Changeset{} = changeset} ->
        teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
        sta_tok = upload_token(conn, "assignment_starter")
        sol_tok = upload_token(conn, "assignment_solution")
        render(conn, "new.html", changeset: changeset, teamsets: teamsets,
          sta_tok: sta_tok, sol_tok: sol_tok)
    end
  end

  def show(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment_for_staff!(id)
    subs = Assignments.list_active_subs(assignment)
    render(conn, "show.html", assignment: %{assignment | subs: subs})
  end

  def edit(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment!(id)
    changeset = Assignments.change_assignment(assignment)
    teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
    sta_tok = upload_token(conn, "assignment_starter")
    sol_tok = upload_token(conn, "assignment_solution")
    render(conn, "edit.html", assignment: assignment,
      changeset: changeset, teamsets: teamsets,
      sta_tok: sta_tok, sol_tok: sol_tok)
  end

  def update(conn, %{"id" => id, "assignment" => assignment_params}) do
    assignment = Assignments.get_assignment!(id)

    case Assignments.update_assignment(assignment, assignment_params) do
      {:ok, assignment} ->
        conn
        |> put_flash(:info, "Assignment updated successfully.")
        |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))

      {:error, %Ecto.Changeset{} = changeset} ->
        teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
        sta_tok = upload_token(conn, "assignment_starter")
        sol_tok = upload_token(conn, "assignment_solution")
        render(conn, "edit.html", assignment: assignment, changeset: changeset,
          teamsets: teamsets, sta_tok: sta_tok, sol_tok: sol_tok)
    end
  end

  def delete(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment!(id)
    {:ok, _assignment} = Assignments.delete_assignment(assignment)

    conn
    |> put_flash(:info, "Assignment deleted successfully.")
    |> redirect(to: Routes.staff_course_path(conn, :show, conn.assigns[:course]))
  end

  def create_fake_subs(conn, %{"id" => _id}) do
    assignment = conn.assigns[:assignment]

    Assignments.create_fake_subs!(assignment, conn.assigns[:current_user])

    conn
    |> put_flash(:info, "Fake submissions created")
    |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))
  end
end

lib/inkfish_web/controllers/staff/bucket_controller.ex
defmodule InkfishWeb.Staff.BucketController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [course: "course_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [bucket: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {"Buckets", :staff_course_bucket, :index, :course}
    when action not in [:index, :new, :create]

  alias Inkfish.Courses
  alias Inkfish.Courses.Bucket

  def index(conn, %{"course_id" => course_id}) do
    conn = assign(conn, :page_title, "List Buckets")
    buckets = Courses.list_buckets(course_id)
    render(conn, "index.html", buckets: buckets)
  end

  def new(conn, %{"course_id" => course_id}) do
    defaults = %Bucket{
      course_id: course_id,
      weight: 100,
    }
    changeset = Courses.change_bucket(defaults)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"course_id" => course_id, "bucket" => bucket_params}) do
    bucket_params = Map.put(bucket_params, "course_id", course_id)

    case Courses.create_bucket(bucket_params) do
      {:ok, bucket} ->
        conn
        |> put_flash(:info, "Bucket created successfully.")
        |> redirect(to: Routes.staff_bucket_path(conn, :show, bucket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    render(conn, "show.html", bucket: bucket)
  end

  def edit(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    changeset = Courses.change_bucket(bucket)
    render(conn, "edit.html", bucket: bucket, changeset: changeset)
  end

  def update(conn, %{"id" => id, "bucket" => bucket_params}) do
    bucket = Courses.get_bucket!(id)

    case Courses.update_bucket(bucket, bucket_params) do
      {:ok, bucket} ->
        conn
        |> put_flash(:info, "Bucket updated successfully.")
        |> redirect(to: Routes.staff_bucket_path(conn, :show, bucket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", bucket: bucket, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    {:ok, _bucket} = Courses.delete_bucket(bucket)

    conn
    |> put_flash(:info, "Bucket deleted successfully.")
    |> redirect(to: Routes.staff_course_bucket_path(conn, :index, bucket.course_id))
  end
end

lib/inkfish_web/controllers/staff/course_controller.ex
defmodule InkfishWeb.Staff.CourseController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [course: "id"]
    when action not in [:index]
  plug Plugs.RequireReg, [staff: true]
    when action not in [:index]

  plug InkfishWeb.Plugs.Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug InkfishWeb.Plugs.Breadcrumb, {:show, :staff, :course}
    when action not in [:index, :new, :create]

  alias Inkfish.Courses
  alias Inkfish.Courses.Course
  alias Inkfish.Grades.Gradesheet
  alias Inkfish.GradingTasks

  def index(conn, _params) do
    courses = Courses.list_courses()
    render(conn, "index.html", courses: courses)
  end

  def show(conn, %{"id" => id}) do
    reg = conn.assigns[:current_reg]
    course = Courses.get_course_for_staff_view!(id)
    task_count = GradingTasks.grader_course_task_count(course, reg)
    render(conn, "show.html", course: course, task_count: task_count)
  end

  def edit(conn, %{"id" => _id}) do
    course = conn.assigns[:course]
    changeset = Courses.change_course(course)
    render(conn, "edit.html", course: course, changeset: changeset)
  end

  def update(conn, %{"id" => _id, "course" => course_params}) do
    course = conn.assigns[:course]

    case Courses.update_course(course, course_params) do
      {:ok, course} ->
        conn
        |> put_flash(:info, "Course updated successfully.")
        |> redirect(to: Routes.staff_course_path(conn, :show, course))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", course: course, changeset: changeset)
    end
  end

  def gradesheet(conn, %{"id" => id}) do
    course = Courses.get_course_for_gradesheet!(id)
    sheet = Gradesheet.from_course(course)
    render(conn, "gradesheet.html", fluid_grid: true,
      course: course, sheet: sheet)
  end

  def tasks(conn, %{"id" => id}) do
    %{current_reg: reg} = conn.assigns

    course = Courses.get_course_for_grading_tasks!(id)
    tasks = course.buckets
    |> Enum.flat_map(fn bucket ->
      Enum.map bucket.assignments, fn asg ->
        subs = Enum.filter asg.subs, fn sub ->
          grade = Enum.find sub.grades, &(&1.grade_column.kind == "feedback")
          mine = (!reg.is_grader || sub.grader_id == reg.id)
          done = (grade && grade.score)
          sub.active && mine && !done
        end
        {asg.id, length(subs)}
      end
    end)
    |> Enum.into(%{})
    render(conn, "tasks.html", course: course, tasks: tasks)
  end
end

lib/inkfish_web/controllers/staff/grading_task_controller.ex
defmodule InkfishWeb.Staff.GradingTaskController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [assignment: "assignment_id"]
  plug Plugs.RequireReg, staff: true

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}

  alias Inkfish.Assignments
  alias Inkfish.Courses
  alias Inkfish.GradingTasks

  def show(conn, _params) do
    %{course: course, assignment: as, current_reg: reg} = conn.assigns

    graders = Courses.list_course_graders(course)

    tasks = Assignments.list_grading_tasks(as)

    user_tasks = Enum.filter tasks, fn sub ->
      sub.grader_id == reg.id
    end

    render(conn, "show.html", graders: graders,
      tasks: tasks, user_tasks: user_tasks)
  end

  def create(conn, _params) do
    %{assignment: as} = conn.assigns

    :ok = Inkfish.GradingTasks.assign_grading_tasks(as)

    conn
    |> put_flash(:info, "Grading has been assigned.")
    |> redirect(to: Routes.staff_assignment_grading_task_path(conn, :show, as))
  end

  def edit(conn, _params) do
    %{course: course, assignment: as} = conn.assigns

    graders = Courses.list_course_graders(course)
    |> Enum.map(fn gdr ->
      InkfishWeb.Staff.RegView.render("reg.json", %{reg: gdr})
    end)
    |> Jason.encode!()

    asg = Assignments.get_assignment_for_grading_tasks!(as.id)
    |> (fn arg ->
      InkfishWeb.Staff.AssignmentView.render("assignment.json", %{assignment: arg})
    end).()
    |> Jason.encode!()

    render(conn, "edit.html", graders: graders, asg: asg)
  end

  def update(conn, _params) do
    %{assignment: as} = conn.assigns

    conn
    |> put_flash(:error, "TODO: Update grading")
    |> redirect(to: Routes.staff_assignment_grading_task_path(conn, :show, as))
  end
end

lib/inkfish_web/views/reg_view.ex
defmodule InkfishWeb.RegView do
  use InkfishWeb, :view

  def render("reg.json", %{reg: reg}) do
    user = get_assoc(reg, :user)

    %{
      user: render_one(user, InkfishWeb.UserView, "user.json"),
    }
  end
end

lib/inkfish_web/views/staff/bucket_view.ex
defmodule InkfishWeb.Staff.BucketView do
  use InkfishWeb, :view

  alias InkfishWeb.Staff.AssignmentView

  def render("bucket.json", %{bucket: bucket}) do
    assignments = get_assoc(bucket, :assignments) || []

    %{
      name: bucket.name,
      assignments: render_many(assignments, AssignmentView, "assignment.json"),
    }
  end
end

lib/inkfish_web/templates/staff/reg/edit.html.eex
<h1>Edit Reg</h1>

<%= form_for @changeset, Routes.staff_reg_path(@conn, :update, @reg), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <p>Course: <%= @course.name %></p>
  </div>

  <div class="form-group">
    <p>User: <%= user_display_name(@reg.user) %></p>
  </div>

  <div class="form-group">
    <div class="form-check">
      <%= checkbox f, :is_grader, class: "form-check-input" %>
      <%= label f, :is_grader %>
      <%= error_tag f, :is_grader %>
    </div>

    <div class="form-check">
      <%= checkbox f, :is_prof, class: "form-check-input" %>
      <%= label f, :is_prof %>
      <%= error_tag f, :is_prof %>
    </div>

    <div class="form-check">
      <%= checkbox f, :is_staff, class: "form-check-input" %>
      <%= label f, :is_staff %>
      <%= error_tag f, :is_staff %>
    </div>

    <div class="form-check">
      <%= checkbox f, :is_student, class: "form-check-input" %>
      <%= label f, :is_student %>
      <%= error_tag f, :is_student %>
    </div>
  </div>

  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

lib/inkfish_web/templates/staff/reg/index.html.eex
<h1>Listing Regs</h1>

<p>
  <%= link "New Reg", to: Routes.staff_course_reg_path(@conn, :new, @course) %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Is grader</th>
      <th>Is prof</th>
      <th>Is staff</th>
      <th>Is student</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for reg <- @regs do %>
  <tr>
    <td><%= link(user_display_name(reg.user),
        to: Routes.staff_reg_path(@conn, :show, reg)) %></td>
    <td><%= reg.is_grader %></td>
    <td><%= reg.is_prof %></td>
    <td><%= reg.is_staff %></td>
    <td><%= reg.is_student %></td>

    <td>
      <%= link "Edit", to: Routes.staff_reg_path(@conn, :edit, reg) %>
      &nbsp;
      <%= link("Delete", to: Routes.staff_reg_path(@conn, :delete, reg),
        method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-sm") %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

lib/inkfish_web/templates/staff/reg/new.html.eex
<h1>New Reg</h1>

<%= form_for @changeset, Routes.staff_course_reg_path(@conn, :create, @course), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <p>Course: <%= @course.name %></p>
  </div>

  <div class="form-group">
    <%= label f, :user_login %>
    <%= text_input(f, :user_login, class: "form-control autosearch",
                   data: [topic: "users"]) %>
    <%= error_tag f, :user_login %>
    <div class="text-muted">
      Username; start typing to search
    </div>
  </div>

  <div class="form-group">
    <div class="form-check">
      <%= checkbox f, :is_grader, class: "form-check-input" %>
      <%= label f, :is_grader %>
      <%= error_tag f, :is_grader %>
    </div>

    <div class="form-check">
      <%= checkbox f, :is_prof, class: "form-check-input" %>
      <%= label f, :is_prof %>
      <%= error_tag f, :is_prof %>
    </div>

    <div class="form-check">
      <%= checkbox f, :is_staff, class: "form-check-input" %>
      <%= label f, :is_staff %>
      <%= error_tag f, :is_staff %>
    </div>

    <div class="form-check">
      <%= checkbox f, :is_student, class: "form-check-input" %>
      <%= label f, :is_student %>
      <%= error_tag f, :is_student %>
    </div>
  </div>

  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

lib/inkfish_web/templates/staff/reg/show.html.eex
<h1>Show Reg</h1>

<p>
  <%= link "Edit", to: Routes.staff_reg_path(@conn, :edit, @reg) %>
</p>

<ul>
  <li>
    <strong>Name:</strong>
    <%= user_display_name(@reg.user) %>

  <li>
    <strong>Is grader:</strong>
    <%= @reg.is_grader %>
  </li>

  <li>
    <strong>Is prof:</strong>
    <%= @reg.is_prof %>
  </li>

  <li>
    <strong>Is staff:</strong>
    <%= @reg.is_staff %>
  </li>

  <li>
    <strong>Is student:</strong>
    <%= @reg.is_student %>
  </li>
</ul>

<h2>Submissions</h2>

<%= Enum.map @course.buckets, fn bucket -> %>
  <h3><%= bucket.name %></h3>

  <table class="table table-striped">
    <thead>
      <th>Active?</th>
      <th>Timestamp</th>
      <th>Score</th>
      <th>Actions</th>
    </thead>
    <tbody>
      <%= Enum.map bucket.assignments, fn as -> %>
        <tr class="table-secondary">
          <td>&nbsp;</td>
          <td colspan="3"><strong><%= as.name %></strong></td>
        </tr>

        <%= Enum.map Enum.reverse((@subs[as.id] || [])), fn sub -> %>
          <tr>
            <td><%= if sub.active, do: "✓" %></td>
            <td><%= link(sub.inserted_at,
                to: Routes.staff_sub_path(@conn, :show, sub)) %></td>
            <td><%= sub.score || "∅" %> / <%= assignment_total_points(as) %></td>
            <td>
              <%= unless sub.active do %>
                <% path = Routes.staff_sub_path(@conn, :update, sub) %>
                <% cset = Inkfish.Subs.change_sub(%{sub | active: true}) %>
                <%= form_for cset, path, fn f -> %>
                  <%= hidden_input f, :active %>
                  <%= submit "Set Active", class: "btn btn-secondary" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>