lib/inkfish_web/router.ex
defmodule InkfishWeb.Router do
  use InkfishWeb, :router
  
  alias InkfishWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plugs.Assign, client_mode: :browser
    plug :fetch_session
    plug Plugs.FetchUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Breadcrumb, {"Home", :page, :index}
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug Plugs.Assign, client_mode: :ajax
    plug :fetch_session
    plug Plugs.FetchUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  
  pipeline :admin do
    plug Plugs.RequireUser, is_admin: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InkfishWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    resources "/session", SessionController, only: [:create, :delete], singleton: true
    post "/session/resume", SessionController, :resume
    resources "/users", UserController, only: [:show, :edit, :update]
    resources "/uploads", UploadController, only: [:create, :show]
    get "/uploads/:id/_meta/thumb", UploadController, :thumb
    get "/uploads/:id/_meta/unpacked/*path", UploadController, :unpacked
    get "/uploads/:id/:name", UploadController, :download
    resources "/courses", CourseController, only: [:index, :show] do
      resources "/join_reqs", JoinReqController, only: [:new, :create]
    end
    resources "/regs", RegController, only: [:show]
    resources "/teams", TeamController, only: [:show]
    resources "/assignments", AssignmentController, only: [:show] do
      resources "/subs", SubController, only: [:new, :create]
    end
    resources "/subs", SubController, only: [:show]
    get "/subs/:id/files", SubController, :files
    resources "/grade_columns", GradeColumnController, only: [:show]
    resources "/grades", GradeController, only: [:show]
  end

  scope "/staff", InkfishWeb.Staff, as: :staff do
    pipe_through :browser

    resources "/courses", CourseController, only: [:index, :show, :edit, :update] do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:index]
      resources "/teamsets", TeamsetController, only: [:index, :new, :create]
      resources "/buckets", BucketController, only: [:index, :new, :create]
      post "/join_reqs/accept_all", JoinReqController, :accept_all
    end
    get "/courses/:id/gradesheet", CourseController, :gradesheet
    get "/courses/:id/tasks", CourseController, :tasks
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/join_reqs", JoinReqController, only: [:show, :delete]
    post "/join_reqs/:id/accept", JoinReqController, :accept
    resources "/teamsets", TeamsetController, except: [:index, :new, :create]
    resources "/buckets", BucketController, except: [:index, :new, :create] do
      resources "/assignments", AssignmentController, only: [:new, :create]
    end
    resources "/assignments", AssignmentController, except: [:index, :new, :create] do
      resources "/grade_columns", GradeColumnController, only: [:index, :new, :create]
      resources "/grading_tasks", GradingTaskController,
        except: [:new, :delete], singleton: true
    end
    post "/assignments/:id/create_fake_subs", AssignmentController, :create_fake_subs
    resources "/grade_columns", GradeColumnController, except: [:index, :new, :create]
    resources "/subs", SubController, only: [:show, :update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [:edit, :show]
    post "/grades/:id/rerun_script", GradeController, :rerun_script
  end

  scope "/admin", InkfishWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    
    resources "/users", UserController, except: [:new, :create]
    post "/users/:id/impersonate", UserController, :impersonate
    resources "/courses", CourseController
    resources "/uploads", UploadController, only: [:index]
  end

  scope "/ajax", InkfishWeb, as: :ajax do
    pipe_through :ajax

    post "/uploads", UploadController, :create
  end

  scope "/ajax/staff", InkfishWeb.Staff, as: :ajax_staff do
    pipe_through :ajax

    resources "/subs", SubController, only: [:update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [] do
      resources "/line_comments", LineCommentController, only: [:create]
    end
    resources "/line_comments", LineCommentController, only: [:show, :update, :delete]
    resources "/teamsets", TeamsetController, only: [] do
      resources "/teams", TeamController, only: [:index, :create]
    end
    resources "/teams", TeamController, only: [:show, :update, :delete]
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/live_dashboard", metrics: InkfishWeb.Telemetry
    end
  end
end

lib/inkfish_web/templates/page/dashboard.html.eex
<div class="row">
  <div class="col">
    <h1>Dashboard</h1>
    <h2>Your Courses</h2>
    <div class="clearfix">
      <div class="float-right">
        <p>
          <%= link("List All Courses", to: Routes.course_path(@conn, :index)) %>
        </p>
      </div>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <td>Course</td>
          <td>Role</td>
          <td>Next Due</td>
        </tr>
      </thead>
      <tbody>
        <%= for reg <- @regs do %>
          <tr>
            <td>
              <%= link(reg.course.name,
                    to: Routes.course_path(@conn, :show, reg.course.id)) %>
              <%= if is_staff?(reg, reg.user) do %>
                (<%= link("Staff View",
                  to: Routes.staff_course_path(@conn, :show, reg.course)) %>)
              <% end %>
            </td>
            <td><%= show_reg_role(reg) %></td>
            <td>
              <% next = Map.get(@dues, reg.course_id) %>
              <%= if next do %>
                <%= next.name %> <br>
                <span class="human-date"><%= next.due %></span>
              <% else %>
                ∅
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

lib/inkfish_web/templates/page/index.html.eex
<div class="row">
  <div class="col">
    <h1>Log In</h1>
    <%= form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
      <div class="form-group">
        <%= label f, :login %>
        <%= text_input f, :login, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= label f, :password %>
        <%= password_input f, :password, class: "form-control" %>
      </div>
      
      <%= submit "Log In", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>