lib/inkfish_web/router.ex
defmodule InkfishWeb.Router do
  use InkfishWeb, :router
  
  alias InkfishWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug Plugs.Assign, client_mode: :browser
    plug :fetch_session
    plug Plugs.FetchUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Breadcrumb, {"Home", :page, :index}
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug Plugs.Assign, client_mode: :ajax
    plug :fetch_session
    plug Plugs.FetchUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  
  pipeline :admin do
    plug Plugs.RequireUser, is_admin: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InkfishWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    resources "/session", SessionController, only: [:create, :delete], singleton: true
    post "/session/resume", SessionController, :resume
    resources "/users", UserController, only: [:show, :edit, :update]
    resources "/uploads", UploadController, only: [:create, :show]
    get "/uploads/:id/_meta/thumb", UploadController, :thumb
    get "/uploads/:id/_meta/unpacked/*path", UploadController, :unpacked
    get "/uploads/:id/:name", UploadController, :download
    resources "/courses", CourseController, only: [:index, :show] do
      resources "/join_reqs", JoinReqController, only: [:new, :create]
    end
    resources "/regs", RegController, only: [:show]
    resources "/teams", TeamController, only: [:show]
    resources "/assignments", AssignmentController, only: [:show] do
      resources "/subs", SubController, only: [:new, :create]
    end
    resources "/subs", SubController, only: [:show]
    get "/subs/:id/files", SubController, :files
    resources "/grade_columns", GradeColumnController, only: [:show]
    resources "/grades", GradeController, only: [:show]
  end

  scope "/staff", InkfishWeb.Staff, as: :staff do
    pipe_through :browser

    resources "/courses", CourseController, only: [:index, :show, :edit, :update] do
      resources "/regs", RegController, only: [:index, :new, :create]
      resources "/join_reqs", JoinReqController, only: [:index]
      resources "/teamsets", TeamsetController, only: [:index, :new, :create]
      resources "/buckets", BucketController, only: [:index, :new, :create]
      post "/join_reqs/accept_all", JoinReqController, :accept_all
    end
    get "/courses/:id/gradesheet", CourseController, :gradesheet
    get "/courses/:id/tasks", CourseController, :tasks
    resources "/regs", RegController, except: [:index, :new, :create]
    resources "/join_reqs", JoinReqController, only: [:show, :delete]
    post "/join_reqs/:id/accept", JoinReqController, :accept
    resources "/teamsets", TeamsetController, except: [:index, :new, :create]
    resources "/buckets", BucketController, except: [:index, :new, :create] do
      resources "/assignments", AssignmentController, only: [:new, :create]
    end
    resources "/assignments", AssignmentController, except: [:index, :new, :create] do
      resources "/grade_columns", GradeColumnController, only: [:index, :new, :create]
      resources "/grading_tasks", GradingTaskController,
        except: [:new, :delete], singleton: true
    end
    post "/assignments/:id/create_fake_subs", AssignmentController, :create_fake_subs
    resources "/grade_columns", GradeColumnController, except: [:index, :new, :create]
    resources "/subs", SubController, only: [:show, :update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [:edit, :show]
    post "/grades/:id/rerun_script", GradeController, :rerun_script
  end

  scope "/admin", InkfishWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    
    resources "/users", UserController, except: [:new, :create]
    post "/users/:id/impersonate", UserController, :impersonate
    resources "/courses", CourseController
    resources "/uploads", UploadController, only: [:index]
  end

  scope "/ajax", InkfishWeb, as: :ajax do
    pipe_through :ajax

    post "/uploads", UploadController, :create
  end

  scope "/ajax/staff", InkfishWeb.Staff, as: :ajax_staff do
    pipe_through :ajax

    resources "/subs", SubController, only: [:update] do
      resources "/grades", GradeController, only: [:create]
    end
    resources "/grades", GradeController, only: [] do
      resources "/line_comments", LineCommentController, only: [:create]
    end
    resources "/line_comments", LineCommentController, only: [:show, :update, :delete]
    resources "/teamsets", TeamsetController, only: [] do
      resources "/teams", TeamController, only: [:index, :create]
    end
    resources "/teams", TeamController, only: [:show, :update, :delete]
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/live_dashboard", metrics: InkfishWeb.Telemetry
    end
  end
end

lib/inkfish_web/controllers/assignment_controller.ex
defmodule InkfishWeb.AssignmentController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [assignment: "id"]
    when action not in [:index, :new, :create]
  plug Plugs.RequireReg

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {:show, :course}

  alias Inkfish.Assignments
  alias Inkfish.Teams

  def show(conn, %{"id" => id}) do
    reg  = conn.assigns[:current_reg]
    asg  = conn.assigns[:assignment]
    subs = Assignments.list_subs_for_reg(id, reg)
    team = Teams.get_active_team(asg, reg)
    render(conn, "show.html", subs: subs, team: team)
  end
end

lib/inkfish_web/controllers/staff/assignment_controller.ex
defmodule InkfishWeb.Staff.AssignmentController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs

  plug Plugs.FetchItem, [bucket: "bucket_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [assignment: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}
    when action not in [:index, :new, :create, :show]

  alias Inkfish.Assignments
  alias Inkfish.Assignments.Assignment

  def new(conn, params) do
    teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
    today = Inkfish.LocalTime.today()
    {:ok, due} = NaiveDateTime.new(Date.add(today, 7), ~T[23:59:59])
    as = %Assignment{
      bucket_id: params["bucket_id"],
      teamset_id: hd(teamsets).id,
      weight: Decimal.new("1.0"),
      due: due,
      allow_git: false,
    }
    changeset = Assignments.change_assignment(as)
    sta_tok = upload_token(conn, "assignment_starter")
    sol_tok = upload_token(conn, "assignment_solution")
    render(conn, "new.html", changeset: changeset, teamsets: teamsets,
      sta_tok: sta_tok, sol_tok: sol_tok)
  end

  def create(conn, %{"assignment" => assignment_params}) do
    case Assignments.create_assignment(assignment_params) do
      {:ok, assignment} ->
        conn
        |> put_flash(:info, "Assignment created successfully.")
        |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))

      {:error, %Ecto.Changeset{} = changeset} ->
        teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
        sta_tok = upload_token(conn, "assignment_starter")
        sol_tok = upload_token(conn, "assignment_solution")
        render(conn, "new.html", changeset: changeset, teamsets: teamsets,
          sta_tok: sta_tok, sol_tok: sol_tok)
    end
  end

  def show(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment_for_staff!(id)
    subs = Assignments.list_active_subs(assignment)
    render(conn, "show.html", assignment: %{assignment | subs: subs})
  end

  def edit(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment!(id)
    changeset = Assignments.change_assignment(assignment)
    teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
    sta_tok = upload_token(conn, "assignment_starter")
    sol_tok = upload_token(conn, "assignment_solution")
    render(conn, "edit.html", assignment: assignment,
      changeset: changeset, teamsets: teamsets,
      sta_tok: sta_tok, sol_tok: sol_tok)
  end

  def update(conn, %{"id" => id, "assignment" => assignment_params}) do
    assignment = Assignments.get_assignment!(id)

    case Assignments.update_assignment(assignment, assignment_params) do
      {:ok, assignment} ->
        conn
        |> put_flash(:info, "Assignment updated successfully.")
        |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))

      {:error, %Ecto.Changeset{} = changeset} ->
        teamsets = Inkfish.Teams.list_teamsets(conn.assigns[:course])
        sta_tok = upload_token(conn, "assignment_starter")
        sol_tok = upload_token(conn, "assignment_solution")
        render(conn, "edit.html", assignment: assignment, changeset: changeset,
          teamsets: teamsets, sta_tok: sta_tok, sol_tok: sol_tok)
    end
  end

  def delete(conn, %{"id" => id}) do
    assignment = Assignments.get_assignment!(id)
    {:ok, _assignment} = Assignments.delete_assignment(assignment)

    conn
    |> put_flash(:info, "Assignment deleted successfully.")
    |> redirect(to: Routes.staff_course_path(conn, :show, conn.assigns[:course]))
  end

  def create_fake_subs(conn, %{"id" => _id}) do
    assignment = conn.assigns[:assignment]

    Assignments.create_fake_subs!(assignment, conn.assigns[:current_user])

    conn
    |> put_flash(:info, "Fake submissions created")
    |> redirect(to: Routes.staff_assignment_path(conn, :show, assignment))
  end
end

lib/inkfish_web/controllers/staff/bucket_controller.ex
defmodule InkfishWeb.Staff.BucketController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [course: "course_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [bucket: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias InkfishWeb.Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {"Buckets", :staff_course_bucket, :index, :course}
    when action not in [:index, :new, :create]

  alias Inkfish.Courses
  alias Inkfish.Courses.Bucket

  def index(conn, %{"course_id" => course_id}) do
    conn = assign(conn, :page_title, "List Buckets")
    buckets = Courses.list_buckets(course_id)
    render(conn, "index.html", buckets: buckets)
  end

  def new(conn, %{"course_id" => course_id}) do
    defaults = %Bucket{
      course_id: course_id,
      weight: 100,
    }
    changeset = Courses.change_bucket(defaults)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"course_id" => course_id, "bucket" => bucket_params}) do
    bucket_params = Map.put(bucket_params, "course_id", course_id)

    case Courses.create_bucket(bucket_params) do
      {:ok, bucket} ->
        conn
        |> put_flash(:info, "Bucket created successfully.")
        |> redirect(to: Routes.staff_bucket_path(conn, :show, bucket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    render(conn, "show.html", bucket: bucket)
  end

  def edit(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    changeset = Courses.change_bucket(bucket)
    render(conn, "edit.html", bucket: bucket, changeset: changeset)
  end

  def update(conn, %{"id" => id, "bucket" => bucket_params}) do
    bucket = Courses.get_bucket!(id)

    case Courses.update_bucket(bucket, bucket_params) do
      {:ok, bucket} ->
        conn
        |> put_flash(:info, "Bucket updated successfully.")
        |> redirect(to: Routes.staff_bucket_path(conn, :show, bucket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", bucket: bucket, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    bucket = Courses.get_bucket!(id)
    {:ok, _bucket} = Courses.delete_bucket(bucket)

    conn
    |> put_flash(:info, "Bucket deleted successfully.")
    |> redirect(to: Routes.staff_course_bucket_path(conn, :index, bucket.course_id))
  end
end

lib/inkfish_web/controllers/staff/course_controller.ex
defmodule InkfishWeb.Staff.CourseController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [course: "id"]
    when action not in [:index]
  plug Plugs.RequireReg, [staff: true]
    when action not in [:index]

  plug InkfishWeb.Plugs.Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug InkfishWeb.Plugs.Breadcrumb, {:show, :staff, :course}
    when action not in [:index, :new, :create]

  alias Inkfish.Courses
  alias Inkfish.Courses.Course
  alias Inkfish.Grades.Gradesheet
  alias Inkfish.GradingTasks

  def index(conn, _params) do
    courses = Courses.list_courses()
    render(conn, "index.html", courses: courses)
  end

  def show(conn, %{"id" => id}) do
    reg = conn.assigns[:current_reg]
    course = Courses.get_course_for_staff_view!(id)
    task_count = GradingTasks.grader_course_task_count(course, reg)
    render(conn, "show.html", course: course, task_count: task_count)
  end

  def edit(conn, %{"id" => _id}) do
    course = conn.assigns[:course]
    changeset = Courses.change_course(course)
    render(conn, "edit.html", course: course, changeset: changeset)
  end

  def update(conn, %{"id" => _id, "course" => course_params}) do
    course = conn.assigns[:course]

    case Courses.update_course(course, course_params) do
      {:ok, course} ->
        conn
        |> put_flash(:info, "Course updated successfully.")
        |> redirect(to: Routes.staff_course_path(conn, :show, course))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", course: course, changeset: changeset)
    end
  end

  def gradesheet(conn, %{"id" => id}) do
    course = Courses.get_course_for_gradesheet!(id)
    sheet = Gradesheet.from_course(course)
    render(conn, "gradesheet.html", fluid_grid: true,
      course: course, sheet: sheet)
  end

  def tasks(conn, %{"id" => id}) do
    %{current_reg: reg} = conn.assigns

    course = Courses.get_course_for_grading_tasks!(id)
    tasks = course.buckets
    |> Enum.flat_map(fn bucket ->
      Enum.map bucket.assignments, fn asg ->
        subs = Enum.filter asg.subs, fn sub ->
          grade = Enum.find sub.grades, &(&1.grade_column.kind == "feedback")
          mine = (!reg.is_grader || sub.grader_id == reg.id)
          done = (grade && grade.score)
          sub.active && mine && !done
        end
        {asg.id, length(subs)}
      end
    end)
    |> Enum.into(%{})
    render(conn, "tasks.html", course: course, tasks: tasks)
  end
end

lib/inkfish_web/controllers/staff/grade_column_controller.ex
defmodule InkfishWeb.Staff.GradeColumnController do
  use InkfishWeb, :controller

  alias InkfishWeb.Plugs
  plug Plugs.FetchItem, [assignment: "assignment_id"]
    when action in [:index, :new, :create]
  plug Plugs.FetchItem, [grade_column: "id"]
    when action not in [:index, :new, :create]

  plug Plugs.RequireReg, staff: true

  alias Plugs.Breadcrumb
  plug Breadcrumb, {"Courses (Staff)", :staff_course, :index}
  plug Breadcrumb, {:show, :staff, :course}
  plug Breadcrumb, {:show, :staff, :assignment}

  alias Inkfish.Grades
  alias Inkfish.Grades.GradeColumn

  def index(conn, _params) do
    grade_columns = Grades.list_grade_columns()
    render(conn, "index.html", grade_columns: grade_columns)
  end

  def new(conn, _params) do
    defaults = %GradeColumn{
      points: Decimal.new("50"),
      base: Decimal.new("50"),
    }
    changeset = Grades.change_grade_column(defaults)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"grade_column" => grade_column_params}) do
    grade_column_params = Map.put(
      grade_column_params, "assignment_id", conn.assigns[:assignment].id)

    case Grades.create_grade_column(grade_column_params) do
      {:ok, grade_column} ->
        conn
        |> put_flash(:info, "Grade_Column created successfully.")
        |> redirect(to: Routes.staff_grade_column_path(conn, :show, grade_column))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    grade_column = Grades.get_grade_column!(id)
    render(conn, "show.html", grade_column: grade_column)
  end

  def edit(conn, %{"id" => id}) do
    grade_column = Grades.get_grade_column!(id)
    changeset = Grades.change_grade_column(grade_column)
    render(conn, "edit.html", grade_column: grade_column, changeset: changeset)
  end

  def update(conn, %{"id" => id, "grade_column" => grade_column_params}) do
    grade_column = Grades.get_grade_column!(id)

    case Grades.update_grade_column(grade_column, grade_column_params) do
      {:ok, grade_column} ->
        conn
        |> put_flash(:info, "Grade_Column updated successfully.")
        |> redirect(to: Routes.staff_grade_column_path(conn, :show, grade_column))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", grade_column: grade_column, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    grade_column = Grades.get_grade_column!(id)
    {:ok, _grade_column} = Grades.delete_grade_column(grade_column)

    conn
    |> put_flash(:info, "Grade column deleted successfully.")
    |> redirect(to: Routes.staff_assignment_path(conn, :show, grade_column.assignment_id))
  end
end

lib/inkfish_web/templates/staff/assignment/edit.html.eex
<h1>Edit Assignment</h1>

<%= render "form.html", Map.put(assigns, :action,
  Routes.staff_assignment_path(@conn, :update, @assignment)) %>

lib/inkfish_web/templates/staff/assignment/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    Bucket: <%= @bucket.name %>
    <%= hidden_input f, :bucket_id %>
  </div>

  <div class="form-group">
    <%= label f, :name %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :desc %>
    <%= textarea f, :desc, class: "form-control" %>
    <%= error_tag f, :desc %>
  </div>

  <div class="form-group">
    <%= label f, :due %>
    <div>
      <%= text_input(f, :due, class: "form-control date-time-picker") %>
    </div>
    <%= error_tag f, :due %>
  </div>

  <div class="form-group">
    <%= label f, :weight %>
    <%= number_input f, :weight, step: "any", class: "form-control" %>
    <%= error_tag f, :weight %>
  </div>

  <div class="form-group">
    <%= label f, :teamset_id %>
    <%= select(f, :teamset_id, Enum.map(@teamsets, &({&1.name, &1.id})),
               class: "form-control")%>
    <%= error_tag f, :teamset_id %>
  </div>

  <div class="form-group">
    <p>Allowed submission methods</p>
    <p class="ml-4">
      <%= label f, :allow_upload, "File Upload" %>
      <%= checkbox f, :allow_upload %>
      <%= error_tag f, :allow_upload %>
      <br>
      <%= label f, :allow_git, "Git Clone" %>
      <%= checkbox f, :allow_git %>
      <%= error_tag f, :allow_git %>
    </p>
  </div>

  <div class="form-group">
    <%= label f, :starter_upload_id %>
    <%= text_input f, :starter_upload_id, class: "form-control", readonly: "readonly" %>
    <%= error_tag f, :starter_upload_id %>
    <div class="file-uploader"
         data-upload-field="assignment_starter_upload_id"
         data-nonce="<%= @sta_tok[:nonce] %>"
         data-token="<%= @sta_tok[:token] %>">
      React loading...
    </div>
  </div>

  <div class="form-group">
    <%= label f, :solution_upload_id %>
    <%= text_input f, :solution_upload_id, class: "form-control", readonly: "readonly" %>
    <%= error_tag f, :solution_upload_id %>
    <div class="file-uploader"
         data-upload-field="assignment_solution_upload_id"
         data-nonce="<%= @sol_tok[:nonce] %>"
         data-token="<%= @sol_tok[:token] %>">
      React loading...
    </div>
  </div>

  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

lib/inkfish_web/templates/staff/assignment/new.html.eex
<h1>New Assignment</h1>

<%= render "form.html", Map.put(assigns, :action,
  Routes.staff_bucket_assignment_path(@conn, :create, @bucket)) %>

lib/inkfish_web/templates/staff/assignment/show.html.eex
<h1>Show Assignment</h1>

<p>
  <%= link("Student View",
    to: Routes.assignment_path(@conn, :show, @assignment)) %> |
  <%= link("Edit Assignment",
    to: Routes.staff_assignment_path(@conn, :edit, @assignment)) %> |
  <%= link("Grading Tasks",
    to: Routes.staff_assignment_grading_task_path(@conn, :show, @assignment)) %>
</p>

<ul>
  <li>
    <strong>Name:</strong>
    <%= @assignment.name %>
  </li>

  <li>
    <strong>Bucket:</strong>
    <%= @bucket.name %>
  </li>

  <li>
    <strong>Teamset:</strong>
    <%= @assignment.teamset.name %>
  </li>

  <li>
    <strong>Due:</strong>
    <span class="human-date">
      <%= show_timestamp(@assignment.due) %>
    </span>
  </li>

  <li>
    <strong>Weight:</strong>
    <%= @assignment.weight %>
  </li>

  <li>
    <strong>Starter:</strong>
    <%= if @assignment.starter_upload do %>
      <%= link(@assignment.starter_upload.name,
            to: Routes.upload_path(@conn, :show, @assignment.starter_upload)) %>
    <% else %>
      ∅
    <% end %>
  </li>

  <li>
    <strong>Solution:</strong>
    <%= if @assignment.solution_upload do %>
      <%= link(@assignment.solution_upload.name,
            to: Routes.upload_path(@conn, :show, @assignment.solution_upload)) %>
    <% else %>
      ∅
    <% end %>
  </li>

  <li>
    <strong>Sub Options:</strong>
    <%= if @assignment.allow_git do %>git<% end %>
    <%= if @assignment.allow_upload do %>upload<% end %>
  </li>
</ul>

<h2>
  Description
  <button class="btn btn-link data-toggle"
          data-toggle="collapse"
          data-target="#asgn-desc">
    Show / Hide
  </button>
</h2>

<div id="asgn-desc" class="collapse">
  <div class="card">
    <div class="card-body">
      <%= trusted_markdown @assignment.desc %>
    </div>
  </div>
</div>

<h2>Grade Columns</h2>

<p>
  <%= link("New Grade Column",
    to: Routes.staff_assignment_grade_column_path(@conn, :new, @assignment)) %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <%= for gcol <- @assignment.grade_columns do %>
      <tr>
        <td><%= link(gcol.name,
            to: Routes.staff_grade_column_path(@conn, :show, gcol)) %></td>
        <td><%= gcol.kind %></td>
        <td><%= gcol.points %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Submissions</h2>

<%= unless @assignment.allow_git || @assignment.allow_upload do %>
  <div>
    <% path = Routes.staff_assignment_path(@conn, :create_fake_subs, @assignment) %>
    <%= form_for @conn, path, fn _f -> %>
      <%= submit("Create Fake Subs", class: "btn btn-secondary",
        data: [confirm: "Are you sure?"]) %>
    <% end %>
</div>
<% end %>

<script>
 function save_grade_path(sub_id) {
   let path = "<%= Routes.ajax_staff_sub_grade_path(@conn, :create, :SubID) %>";
   return path.replace('SubID', sub_id);
 }
</script>

<table class="table table-striped">
  <thead>
    <th>Student</th>
    <%= for gcol <- @assignment.grade_columns do %>
      <th>
        <%= gcol.name %>
        <%= if gcol.kind == "number" do %>
          <span class="toggle-number-inputs" data-grade-column-id="<%= gcol.id %>">
            <!-- react component from gcolade_columns/number-input.jsx -->
            [react]
          </span>
        <% end %>
      </th>
    <% end %>
    <th>Total Grade</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <%= for sub <- @assignment.subs do %>
      <tr>
        <td><%= link(user_display_name(sub.reg.user),
            to: Routes.staff_reg_path(@conn, :show, sub.reg)) %></td>
        <%= for gcol <- @assignment.grade_columns do %>
          <% grade = Enum.find(sub.grades, &(&1.grade_column_id == gcol.id)) %>
          <td>
            <%= case gcol.kind do %>
              <% "number" -> %>
                <div class="number-grade-cell"
                     data-score="<%= (grade && grade.score) || 0 %>"
                     data-points="<%= gcol.points %>"
                     data-sub-id="<%= sub.id %>"
                     data-grade-column-id="<%= gcol.id %>">
                  <!-- React component: grade_columns/number-input.jsx -->
                  <%= show_score(@conn, grade) %>
                </div>
              <% "feedback" -> %>
                <%= if grade do %>
                  <%= show_score(@conn, grade) %> / <%= gcol.points %>
                  <%= link("Edit", to: Routes.staff_grade_path(@conn, :edit, grade)) %>
                <% else %>
                  <% grade = %Inkfish.Grades.Grade{
                    grade_column_id: gcol.id, sub_id: sub.id
                  } %>
                  <% cset = Inkfish.Grades.change_grade(grade) %>
                  <% action = Routes.staff_sub_grade_path(@conn, :create, sub.id) %>
                  <%= form_for cset, action, fn f -> %>
                    <%= hidden_input f, :sub_id %>
                    <%= hidden_input f, :grade_column_id %>
                    <%= submit "Create", class: "btn btn-secondary btn-sm" %>
                  <% end %>
                <% end %>
              <% _else -> %>
                <%= show_score(@conn, grade) %> / <%= gcol.points %>
            <% end %>
          </td>
        <% end %>
        <td><%= show_score(@conn, sub) %> / <%= assignment_total_points(@assignment) %></td>
        <td>
          <%= link("View", to: Routes.staff_sub_path(@conn, :show, sub)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>